### PR TITLE
masquerade and more async methods

### PR DESCRIPTION
**Pull request by michaelkryukov**
Changes:

- Added masquerading mock classes as motor's original, so checks like `isinstance(collection, AsyncIOMotorCollection)` won't fail. It's possible there will still be issues if you expected to use tornado classes instead of asyncio, but I will wait for actual cases to somehow solve this.
- Added some async methods for collection. 
- Added test that checks basic compatibility with beanie ODM.

Notes:
- Inspired by #1.

### CODE REVIEW

**Comment by tclasen** [comment]
Hey again! Here is my example code base that prompted the previous PR if you want to test against this. If you look at the init_mongo function you can see I'm passing in an arg and a kwarg. If I remove those, your branch les me pass unit tests 100%. Could we also add something to consume excess *args and **kwargs when initializing the client?

https://github.com/tclasen/fastapiplayground

**Comment by tclasen** [comment]
And also, a HUGE thank you for even making this library. Unit testing async mongo has been such a pain for the longest time. Despite your repo only being a few days old, it is the most complete / working implementation on the market right now.

**Comment by michaelkryukov** [comment]
Pretty much all the credit goes to [mongomock](https://github.com/mongomock/mongomock), they did most of the job 😄. Nice to see that I'm not the only one who needed a viable mock for async mongo too. I added `*args, **kwargs` to AsyncMongoMockClient's `__init__`. This should fix mocking with `AsyncMongoMockClient`.

**Comment by tclasen** [comment]
I just confirmed your newest commit passes all tests in my repo using Beanie.

**Pull request merged**
